train_dir   : '/Users/lucascurtin/Desktop/QGNN Repos/HepTrkX-quantum/data/two_events/train'
valid_dir   : '/Users/lucascurtin/Desktop/QGNN Repos/HepTrkX-quantum/data/two_events/valid'
dataset     : 'mu200_1pT'
log_dir     : 'logs/test_CGNN/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 32
n_valid     : 16
n_train     : 16
lr_c        : 0.01
batch_size  : 1
n_iters     : 3
n_epoch     : 30
TEST_every  : 50
hid_dim     : 4
network     : 'CGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 4
log_verbosity: 2