train_dir   : '/Users/lucascurtin/Desktop/QGNN Repos/HepTrkX-quantum/data/10_events/train'
valid_dir   : '/Users/lucascurtin/Desktop/QGNN Repos/HepTrkX-quantum/data/10_events/valid'
dataset     : 'self'
log_dir     : 'logs/test_CGNN/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 160
n_valid     : 20
n_train     : 20
lr_c        : 0.01
batch_size  : 1
n_iters     : 3
n_epoch     : 30
TEST_every  : 20
hid_dim     : 4
network     : 'CGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 4
log_verbosity: 2