train_dir   : '/home/xzcaplcu/repo/data_copy/tuysuz_100_events/train'
valid_dir   : '/home/xzcaplcu/repo/data_copy/tuysuz_100_events/valid'
dataset     : 'TuysuzPaper'
log_dir     : 'logs/test_CGNN/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 1600
n_valid     : 10
n_train     : 10
lr_c        : 0.01
batch_size  : 1
n_iters     : 1
n_epoch     : 20
TEST_every  : 80
hid_dim     : 4
network     : 'CGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 4
log_verbosity: 2
