train_dir   : '/Users/lucascurtin/Desktop/QGNN Repos/qtrkx-gnn-tracking/data_personal/train_0'
valid_dir   : '/Users/lucascurtin/Desktop/QGNN Repos/qtrkx-gnn-tracking/data_personal/valid_0'
dataset     : 'TuysuzPaper'
log_dir     : '/Users/lucascurtin/Desktop/QGNN Repos/qtrkx-gnn-tracking/logs/test_CGNN/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 100
n_valid     : 20
n_train     : 80
lr_c        : 0.01
batch_size  : 1
n_iters     : 1
n_epoch     : 20
TEST_every  : 40
hid_dim     : 4
network     : 'CGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 4
log_verbosity: 2
