train_dir   : '/Users/lucascurtin/Desktop/QGNN Repos/qtrkx-gnn-tracking/data_personal/train_graphs'
valid_dir   : '/Users/lucascurtin/Desktop/QGNN Repos/qtrkx-gnn-tracking/data_personal/valid_graphs'
dataset     : 'TuysuzPaper'
log_dir     : '/Users/lucascurtin/Desktop/QGNN Repos/qtrkx-gnn-tracking/logs/test_QGNN/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 10
n_valid     : 2
n_train     : 8
batch_size  : 1
lr_c        : 0.01
n_iters     : 3
n_epoch     : 3
TEST_every  : 1
hid_dim     : 4
network     : 'QGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 4
log_verbosity: 2
EN_qc:
  PQC_id  : 'MPS'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_last'
  n_layers : 1
  repetitions: 0
  n_qubits: 4
NN_qc:
  PQC_id  : 'MPS'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_last'
  n_layers : 1
  repetitions: 0
  n_qubits: 4