train_dir   : '/home/xzcaplcu/repo/qtrkx-gnn-tracking/data_personal/train_new'
valid_dir   : '/home/xzcaplcu/repo/qtrkx-gnn-tracking/data_personal/valid_new'
dataset     : 'TuysuzPaper'
log_dir     : '/home/xzcaplcu/repo/qtrkx-gnn-tracking/logs/test_CGNN/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 100
n_valid     : 50
n_train     : 50
batch_size  : 1 
lr_c        : 0.01
n_iters     : 3
n_epoch     : 20
TEST_every  : 50
hid_dim     : 4
network     : 'QGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 4
log_verbosity: 2
EN_qc:
  PQC_id  : '10'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_all'
  n_layers : 3
  repetitions: 0
  n_qubits: 4
NN_qc:
  PQC_id  : '10'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_all'
  n_layers : 3
  repetitions: 0
  n_qubits: 4