train_dir   : '/home/xzcaplcu/repo/qtrkx-gnn-tracking/data_personal/train_graphs'
valid_dir   : '/home/xzcaplcu/repo/qtrkx-gnn-tracking/data_personal/valid_graphs'
dataset     : 'TuysuzPaper'
log_dir     : '/home/xzcaplcu/repo/qtrkx-gnn-tracking/logs/test_QGNN/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 100
n_valid     : 20
n_train     : 80
lr_c        : 0.01
batch_size  : 1
n_iters     : 3
n_epoch     : 30
TEST_every  : 50
hid_dim     : 4
network     : 'CGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 4
log_verbosity: 2
