train_dir : /home/xzcaplcu/repo/qtrkx-gnn-tracking/data_personal/tuysuz_original/train 
valid_dir : /home/xzcaplcu/repo/qtrkx-gnn-tracking/data_personal/tuysuz_original/valid 
dataset : mu200_1pT 
log_dir : logs/test_CGNN/runalpha/ 
run_type : new_run 
gpu : -1 
n_files : 100 
n_valid : 50 
n_train : 50 
lr_c : 0.01 
batch_size : 1 
n_iters : 3 
n_epoch : 20 
TEST_every : 50 
hid_dim : 4 
network : CGNN 
optimizer : Adam 
loss_func : BinaryCrossentropy 
n_thread : 4 
log_verbosity : 2 
